version: 2

build:
  os: "ubuntu-24.04"
  apt_packages:
    - zip
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install mkdocs-material
    build:
      html:
        - ./scripts/build_readthedocs_site.sh

mkdocs:
  configuration: config/zh/mkdocs.yml
