version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install mkdocs-material
    build:
      html:
        - cat config/$(echo "$READTHEDOCS_LANGUAGE"|cut -d'-' -f1)/mkdocs.yml
        - python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file config/$(echo "$READTHEDOCS_LANGUAGE"|cut -d'-' -f1)/mkdocs.yml

mkdocs:
  configuration: config/zh/mkdocs.yml
