# Auto-generated during packaging, do not edit this file manually.
__version__ = "1.0.0"
__git_commit__ = "8fef99188d9bde967642ff8da3e9a2d5ba52c87f"
__git_branch__ = "main"
__git_tag__ = "v1.0.0-10-g8fef991"
__git_commit_date__ = "2025-02-15 19:00:55 +0800"
