# Auto-generated during packaging, do not edit this file manually.
__version__ = "1.0.1"
__git_commit__ = "79210eb558c890bcc12f3795ea3f54232f4d82b2"
__git_branch__ = "main"
__git_tag__ = "v1.0.1-1-g79210eb"
__git_commit_date__ = "2025-02-17 23:48:46 +0800"
